# Generated by Django 4.1 on 2022-09-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_rename_questions_text_question_question_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="end_date",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="date ending"
            ),
        ),
    ]
