# Generated by Django 4.1 on 2022-09-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_vote"),
    ]

    operations = [
        migrations.RemoveField(model_name="choice", name="votes",),
    ]
